// Generated by .claude/tools/contracts.mjs from .claude/contracts/*.md. Do not edit;
// change the contract frontmatter and run `npm run contracts`.
window.ARK = {
  "generatedAt": "2026-10-01T12:14:26.293Z",
  "stages": [
    "ready-for-refinement",
    "ready-for-testing",
    "ready-for-playwright",
    "ready-for-white-glove"
  ],
  "contracts": [
    {
      "id": "custom-reporter",
      "title": "Custom Reporter",
      "kind": "capability",
      "stage": "ready-for-playwright",
      "owner": "RobertRiceJR",
      "status": "draft",
      "version": "0.1.0",
      "minted": null,
      "updated": "2026-10-01",
      "file": ".claude/contracts/custom-reporter.md",
      "depth": 0,
      "depends_on": [],
      "provides": [
        {
          "name": "automation-results",
          "kind": "file-format",
          "ref": "src/contracts/automation-results.ts",
          "refExists": false
        }
      ],
      "gate": [
        "Implements Playwright's Reporter interface and is registered in playwright.config.ts",
        "Writes one automation-results file per run, valid against its schema",
        "Each result carries test id, project, status, duration, retries, tags, and attachment paths"
      ],
      "code": [],
      "knowledge": [],
      "consumers": [
        "custom-dashboard",
        "ready-for-white-glove"
      ],
      "blockedBy": [],
      "rootBlockers": [],
      "mintable": true
    },
    {
      "id": "ready-for-refinement",
      "title": "Ready for Refinement",
      "kind": "orchestrator",
      "stage": "ready-for-refinement",
      "owner": "RobertRiceJR",
      "status": "draft",
      "version": "0.1.0",
      "minted": null,
      "updated": "2026-10-01",
      "file": ".claude/contracts/ready-for-refinement.md",
      "depth": 0,
      "depends_on": [],
      "provides": [
        {
          "name": "refinement-intake",
          "kind": "schema",
          "ref": "src/contracts/stages/refinement.ts",
          "refExists": false
        },
        {
          "name": "refinement-exit",
          "kind": "schema",
          "ref": "src/contracts/stages/refinement.ts",
          "refExists": false
        }
      ],
      "gate": [
        "Entry criteria for a story are written as a typed schema (refinement-intake)",
        "Exit criteria are typed, and every authored test case traces to an acceptance criterion",
        "A story missing acceptance criteria is rejected at intake, not passed downstream"
      ],
      "code": [],
      "knowledge": [],
      "consumers": [
        "ready-for-testing",
        "tc-author"
      ],
      "blockedBy": [],
      "rootBlockers": [],
      "mintable": true
    },
    {
      "id": "tc-author",
      "title": "TC-Author",
      "kind": "capability",
      "stage": "ready-for-refinement",
      "owner": "RobertRiceJR",
      "status": "draft",
      "version": "0.1.0",
      "minted": null,
      "updated": "2026-10-01",
      "file": ".claude/contracts/tc-author.md",
      "depth": 1,
      "depends_on": [
        {
          "id": "ready-for-refinement",
          "version": "^0.1.0",
          "uses": [
            "refinement-intake"
          ],
          "satisfied": false
        }
      ],
      "provides": [
        {
          "name": "test-case-metadata",
          "kind": "schema",
          "ref": "src/contracts/test-case.ts",
          "refExists": false
        }
      ],
      "gate": [
        "Every authored test case has an id, title, steps, expected result, and acceptance-criterion trace",
        "Test-case metadata carries the fields runner-tag-topology derives tags from (area, priority, type)",
        "Authoring the same story twice yields the same test-case ids"
      ],
      "code": [],
      "knowledge": [],
      "consumers": [
        "ready-for-testing",
        "runner-tag-topology"
      ],
      "blockedBy": [
        "ready-for-refinement"
      ],
      "rootBlockers": [
        "ready-for-refinement"
      ],
      "mintable": false
    },
    {
      "id": "ready-for-testing",
      "title": "Ready for Testing",
      "kind": "orchestrator",
      "stage": "ready-for-testing",
      "owner": "RobertRiceJR",
      "status": "draft",
      "version": "0.1.0",
      "minted": null,
      "updated": "2026-10-01",
      "file": ".claude/contracts/ready-for-testing.md",
      "depth": 2,
      "depends_on": [
        {
          "id": "ready-for-refinement",
          "version": "^0.1.0",
          "uses": [
            "refinement-exit"
          ],
          "satisfied": false
        },
        {
          "id": "tc-author",
          "version": "^0.1.0",
          "uses": [
            "test-case-metadata"
          ],
          "satisfied": false
        }
      ],
      "provides": [
        {
          "name": "pr-analysis",
          "kind": "report",
          "ref": "src/contracts/stages/testing.ts",
          "refExists": false
        },
        {
          "name": "testing-exit",
          "kind": "schema",
          "ref": "src/contracts/stages/testing.ts",
          "refExists": false
        }
      ],
      "gate": [
        "Stage starts only on a merged PR linked to a refined story",
        "PR analysis maps changed files to the affected test cases",
        "tc-judge returns a pass/fail verdict with reasons for every authored test case",
        "testing-exit lists only judged-passing test cases"
      ],
      "code": [],
      "knowledge": [],
      "consumers": [
        "ready-for-playwright"
      ],
      "blockedBy": [
        "ready-for-refinement",
        "tc-author"
      ],
      "rootBlockers": [
        "ready-for-refinement"
      ],
      "mintable": false
    },
    {
      "id": "runner-tag-topology",
      "title": "Runner Tag Topology",
      "kind": "capability",
      "stage": "ready-for-playwright",
      "owner": "RobertRiceJR",
      "status": "draft",
      "version": "0.1.0",
      "minted": null,
      "updated": "2026-10-01",
      "file": ".claude/contracts/runner-tag-topology.md",
      "depth": 2,
      "depends_on": [
        {
          "id": "tc-author",
          "version": "^0.1.0",
          "uses": [
            "test-case-metadata"
          ],
          "satisfied": false
        }
      ],
      "provides": [
        {
          "name": "tag-vocabulary",
          "kind": "tag-set",
          "ref": "src/contracts/tags.ts",
          "refExists": false
        }
      ],
      "gate": [
        "The tag vocabulary is a closed, typed set derived from test-case metadata fields",
        "Every spec has exactly one @area tag and one @priority tag",
        "An unknown tag fails `npx playwright test --list`"
      ],
      "code": [],
      "knowledge": [],
      "consumers": [
        "custom-dashboard",
        "ready-for-playwright"
      ],
      "blockedBy": [
        "tc-author"
      ],
      "rootBlockers": [
        "ready-for-refinement"
      ],
      "mintable": false
    },
    {
      "id": "custom-dashboard",
      "title": "Custom Dashboard",
      "kind": "capability",
      "stage": "ready-for-white-glove",
      "owner": "RobertRiceJR",
      "status": "draft",
      "version": "0.1.0",
      "minted": null,
      "updated": "2026-10-01",
      "file": ".claude/contracts/custom-dashboard.md",
      "depth": 3,
      "depends_on": [
        {
          "id": "runner-tag-topology",
          "version": "^0.1.0",
          "uses": [
            "tag-vocabulary"
          ],
          "satisfied": false
        },
        {
          "id": "custom-reporter",
          "version": "^0.1.0",
          "uses": [
            "automation-results"
          ],
          "satisfied": false
        }
      ],
      "provides": [
        {
          "name": "results-dashboard",
          "kind": "report",
          "ref": ".claude/dashboards/results/index.html",
          "refExists": false
        }
      ],
      "gate": [
        "Renders any automation-results file with no build step (vanilla HTML/CSS/JS)",
        "Filters and groups by every tag dimension in the tag vocabulary",
        "Works in light and dark themes and at phone width"
      ],
      "code": [],
      "knowledge": [],
      "consumers": [
        "ready-for-white-glove"
      ],
      "blockedBy": [
        "runner-tag-topology",
        "custom-reporter"
      ],
      "rootBlockers": [
        "ready-for-refinement",
        "custom-reporter"
      ],
      "mintable": false
    },
    {
      "id": "ready-for-playwright",
      "title": "Ready for Playwright",
      "kind": "orchestrator",
      "stage": "ready-for-playwright",
      "owner": "RobertRiceJR",
      "status": "draft",
      "version": "0.1.0",
      "minted": null,
      "updated": "2026-10-01",
      "file": ".claude/contracts/ready-for-playwright.md",
      "depth": 3,
      "depends_on": [
        {
          "id": "ready-for-testing",
          "version": "^0.1.0",
          "uses": [
            "testing-exit"
          ],
          "satisfied": false
        },
        {
          "id": "runner-tag-topology",
          "version": "^0.1.0",
          "uses": [
            "tag-vocabulary"
          ],
          "satisfied": false
        }
      ],
      "provides": [
        {
          "name": "run-plan",
          "kind": "schema",
          "ref": "src/contracts/stages/playwright.ts",
          "refExists": false
        },
        {
          "name": "playwright-exit",
          "kind": "schema",
          "ref": "src/contracts/stages/playwright.ts",
          "refExists": false
        }
      ],
      "gate": [
        "Every judged test case maps to at least one Playwright spec",
        "The run plan selects specs by tag only, never by file path",
        "`npx playwright test` runs the plan across chromium, firefox, and webkit"
      ],
      "code": [],
      "knowledge": [],
      "consumers": [
        "ready-for-white-glove"
      ],
      "blockedBy": [
        "ready-for-testing",
        "runner-tag-topology"
      ],
      "rootBlockers": [
        "ready-for-refinement"
      ],
      "mintable": false
    },
    {
      "id": "ready-for-white-glove",
      "title": "Ready for White Glove",
      "kind": "orchestrator",
      "stage": "ready-for-white-glove",
      "owner": "RobertRiceJR",
      "status": "draft",
      "version": "0.1.0",
      "minted": null,
      "updated": "2026-10-01",
      "file": ".claude/contracts/ready-for-white-glove.md",
      "depth": 4,
      "depends_on": [
        {
          "id": "ready-for-playwright",
          "version": "^0.1.0",
          "uses": [
            "playwright-exit"
          ],
          "satisfied": false
        },
        {
          "id": "custom-reporter",
          "version": "^0.1.0",
          "uses": [
            "automation-results"
          ],
          "satisfied": false
        },
        {
          "id": "custom-dashboard",
          "version": "^0.1.0",
          "uses": [
            "results-dashboard"
          ],
          "satisfied": false
        }
      ],
      "provides": [
        {
          "name": "compiled-report",
          "kind": "report",
          "ref": "src/contracts/stages/white-glove.ts",
          "refExists": false
        }
      ],
      "gate": [
        "One compiled report per story traces story to test cases to verdicts to run results",
        "Every failure in the report links to its trace and screenshot",
        "The report builds with no manual editing"
      ],
      "code": [],
      "knowledge": [],
      "consumers": [],
      "blockedBy": [
        "ready-for-playwright",
        "custom-reporter",
        "custom-dashboard"
      ],
      "rootBlockers": [
        "ready-for-refinement",
        "custom-reporter"
      ],
      "mintable": false
    }
  ],
  "issues": []
};
